-- Référentiel des catégories (source : src/db/categories.ts).
-- Insère les catégories manquantes ; pour celles qui existent déjà, seul l'ordre
-- d'affichage est réaligné : un libellé renommé depuis le backend est conservé.
INSERT INTO "categories" ("slug", "label", "accent", "tint", "sort") VALUES
  ('alimentation', 'Alimentation / Épicerie', '#E0A63C', '#f6efdc', 1),
  ('epicerie-fine', 'Épicerie fine – Produits du terroir', '#6FB0C6', '#e7f0f3', 2),
  ('supermarche', 'Supermarché – Grande distribution', '#9a6638', '#f4ebda', 3),
  ('boulangerie', 'Boulangerie – Pâtisserie', '#2C6FB3', '#eaf0f6', 4),
  ('boucherie-charcuterie', 'Boucherie – Charcuterie', '#5a7a5a', '#eef0ec', 5),
  ('poissonnerie', 'Poissonnerie', '#7a6f9c', '#efe9f3', 6),
  ('primeur', 'Primeur – Fruits & Légumes', '#c98a2e', '#f7efe0', 7),
  ('fromagerie', 'Fromagerie – Crèmerie', '#3f8aa3', '#e6eff2', 8),
  ('cave', 'Cave – Vins & Spiritueux', '#E0A63C', '#f6efdc', 9),
  ('brasserie-artisanale', 'Brasserie artisanale – Boissons', '#6FB0C6', '#e7f0f3', 10),
  ('chocolaterie', 'Chocolaterie – Confiserie', '#9a6638', '#f4ebda', 11),
  ('glacier-salon-de-the', 'Glacier – Salon de thé', '#2C6FB3', '#eaf0f6', 12),
  ('traiteur', 'Traiteur', '#5a7a5a', '#eef0ec', 13),
  ('restauration', 'Restauration', '#7a6f9c', '#efe9f3', 14),
  ('pizzeria', 'Pizzeria', '#c98a2e', '#f7efe0', 15),
  ('restauration-rapide', 'Restauration rapide – Food truck', '#3f8aa3', '#e6eff2', 16),
  ('cafe-bar', 'Café – Bar – Brasserie', '#E0A63C', '#f6efdc', 17),
  ('mode-beaute', 'Mode & Beauté', '#6FB0C6', '#e7f0f3', 18),
  ('mode-vetements', 'Mode & Vêtements', '#9a6638', '#f4ebda', 19),
  ('lingerie', 'Lingerie', '#2C6FB3', '#eaf0f6', 20),
  ('vetements-enfants', 'Vêtements enfants', '#5a7a5a', '#eef0ec', 21),
  ('chaussures-maroquinerie', 'Chaussures – Maroquinerie', '#7a6f9c', '#efe9f3', 22),
  ('bijouterie', 'Bijouterie – Horlogerie', '#c98a2e', '#f7efe0', 23),
  ('coiffure', 'Coiffure', '#3f8aa3', '#e6eff2', 24),
  ('barbier', 'Barbier', '#E0A63C', '#f6efdc', 25),
  ('esthetique', 'Esthétique – Institut', '#6FB0C6', '#e7f0f3', 26),
  ('onglerie', 'Onglerie – Prothésie ongulaire', '#9a6638', '#f4ebda', 27),
  ('parfumerie', 'Parfumerie', '#2C6FB3', '#eaf0f6', 28),
  ('bien-etre', 'Bien-être – Spa – Massage', '#5a7a5a', '#eef0ec', 29),
  ('optique', 'Optique', '#7a6f9c', '#efe9f3', 30),
  ('tatouage', 'Tatouage – Piercing', '#c98a2e', '#f7efe0', 31),
  ('bazar-discount', 'Bazar – Discount – Équipement de la maison', '#3f8aa3', '#e6eff2', 32),
  ('decoration', 'Décoration – Ameublement', '#E0A63C', '#f6efdc', 33),
  ('cuisiniste', 'Cuisines – Salles de bain', '#6FB0C6', '#e7f0f3', 34),
  ('literie', 'Literie', '#9a6638', '#f4ebda', 35),
  ('arts-de-la-table', 'Arts de la table – Cadeaux', '#2C6FB3', '#eaf0f6', 36),
  ('electromenager-multimedia', 'Électroménager – Multimédia', '#5a7a5a', '#eef0ec', 37),
  ('fleuriste', 'Fleuriste', '#7a6f9c', '#efe9f3', 38),
  ('jardinerie', 'Jardinerie – Motoculture', '#c98a2e', '#f7efe0', 39),
  ('bricolage-jardinage', 'Bricolage – Jardinage', '#3f8aa3', '#e6eff2', 40),
  ('animalerie', 'Animalerie – Services animaliers', '#E0A63C', '#f6efdc', 41),
  ('artisanat', 'Artisanat', '#6FB0C6', '#e7f0f3', 42),
  ('batiment', 'Bâtiment – Rénovation', '#9a6638', '#f4ebda', 43),
  ('architecte', 'Architecte – Maître d''œuvre', '#2C6FB3', '#eaf0f6', 44),
  ('maconnerie', 'Maçonnerie – Gros œuvre', '#5a7a5a', '#eef0ec', 45),
  ('couverture-toiture', 'Couverture – Toiture – Zinguerie', '#7a6f9c', '#efe9f3', 46),
  ('plomberie', 'Plomberie – Chauffage', '#c98a2e', '#f7efe0', 47),
  ('electricite', 'Électricité', '#3f8aa3', '#e6eff2', 48),
  ('isolation-energie', 'Isolation – Énergies renouvelables', '#E0A63C', '#f6efdc', 49),
  ('menuiserie', 'Menuiserie – Ébénisterie', '#6FB0C6', '#e7f0f3', 50),
  ('serrurerie-metallerie', 'Serrurerie – Métallerie', '#9a6638', '#f4ebda', 51),
  ('carrelage-sols', 'Carrelage – Revêtements de sols', '#2C6FB3', '#eaf0f6', 52),
  ('peinture', 'Peinture – Décoration intérieure', '#5a7a5a', '#eef0ec', 53),
  ('paysagiste', 'Paysagiste – Espaces verts', '#7a6f9c', '#efe9f3', 54),
  ('depannage-multiservices', 'Dépannage – Multiservices', '#c98a2e', '#f7efe0', 55),
  ('automobile', 'Automobile – Garage', '#3f8aa3', '#e6eff2', 56),
  ('carrosserie', 'Carrosserie', '#E0A63C', '#f6efdc', 57),
  ('controle-technique', 'Contrôle technique', '#6FB0C6', '#e7f0f3', 58),
  ('station-service-lavage', 'Station-service – Lavage auto', '#9a6638', '#f4ebda', 59),
  ('location-vehicules', 'Location de véhicules', '#2C6FB3', '#eaf0f6', 60),
  ('cycles-motos', 'Cycles – Motos', '#5a7a5a', '#eef0ec', 61),
  ('auto-ecole', 'Auto-école', '#7a6f9c', '#efe9f3', 62),
  ('taxi-vtc', 'Taxi – VTC', '#c98a2e', '#f7efe0', 63),
  ('sante', 'Santé – Pharmacie', '#3f8aa3', '#e6eff2', 64),
  ('medical', 'Médical – Paramédical', '#E0A63C', '#f6efdc', 65),
  ('audioprothese', 'Audioprothèse', '#6FB0C6', '#e7f0f3', 66),
  ('veterinaire', 'Vétérinaire', '#9a6638', '#f4ebda', 67),
  ('banque-assurance', 'Banque – Assurance', '#2C6FB3', '#eaf0f6', 68),
  ('assurance', 'Assurance – Mutuelle – Prévoyance', '#5a7a5a', '#eef0ec', 69),
  ('courtier-credit', 'Courtier – Crédit – Financement', '#7a6f9c', '#efe9f3', 70),
  ('immobilier', 'Immobilier', '#c98a2e', '#f7efe0', 71),
  ('diagnostic-immobilier', 'Diagnostic immobilier – Expertise', '#3f8aa3', '#e6eff2', 72),
  ('services', 'Services', '#E0A63C', '#f6efdc', 73),
  ('services-a-la-personne', 'Services à la personne – Aide à domicile', '#6FB0C6', '#e7f0f3', 74),
  ('pressing-retouches', 'Pressing – Retouches – Cordonnerie', '#9a6638', '#f4ebda', 75),
  ('photographe', 'Photographe – Vidéo', '#2C6FB3', '#eaf0f6', 76),
  ('pompes-funebres', 'Pompes funèbres', '#5a7a5a', '#eef0ec', 77),
  ('agence-voyages', 'Agence de voyages', '#7a6f9c', '#efe9f3', 78),
  ('demenagement', 'Déménagement – Garde-meubles', '#c98a2e', '#f7efe0', 79),
  ('comptabilite', 'Comptabilité – Gestion', '#3f8aa3', '#e6eff2', 80),
  ('juridique', 'Juridique – Notaire', '#E0A63C', '#f6efdc', 81),
  ('conseil', 'Conseil aux entreprises', '#6FB0C6', '#e7f0f3', 82),
  ('communication', 'Communication – Web – Marketing', '#9a6638', '#f4ebda', 83),
  ('imprimerie-enseignes', 'Imprimerie – Enseignes – Signalétique', '#2C6FB3', '#eaf0f6', 84),
  ('informatique', 'Informatique – Téléphonie', '#5a7a5a', '#eef0ec', 85),
  ('nettoyage', 'Nettoyage – Entretien', '#7a6f9c', '#efe9f3', 86),
  ('transport', 'Transport – Logistique', '#c98a2e', '#f7efe0', 87),
  ('securite', 'Sécurité', '#3f8aa3', '#e6eff2', 88),
  ('coworking', 'Coworking – Bureaux', '#E0A63C', '#f6efdc', 89),
  ('interim-rh', 'Intérim – Ressources humaines', '#6FB0C6', '#e7f0f3', 90),
  ('recyclage-dechets', 'Recyclage – Gestion des déchets', '#9a6638', '#f4ebda', 91),
  ('librairie-papeterie', 'Librairie – Papeterie – Presse', '#2C6FB3', '#eaf0f6', 92),
  ('tabac-presse', 'Tabac – Presse – Loto', '#5a7a5a', '#eef0ec', 93),
  ('jouets-puericulture', 'Jouets – Puériculture', '#7a6f9c', '#efe9f3', 94),
  ('sport-loisirs', 'Sport – Loisirs', '#c98a2e', '#f7efe0', 95),
  ('articles-de-sport', 'Articles de sport', '#3f8aa3', '#e6eff2', 96),
  ('fitness', 'Salle de sport – Fitness', '#E0A63C', '#f6efdc', 97),
  ('culture-arts', 'Culture – Arts', '#6FB0C6', '#e7f0f3', 98),
  ('education-formation', 'Éducation – Formation', '#9a6638', '#f4ebda', 99),
  ('tourisme-hotellerie', 'Tourisme – Hôtellerie', '#2C6FB3', '#eaf0f6', 100),
  ('evenementiel', 'Événementiel', '#5a7a5a', '#eef0ec', 101),
  ('industrie', 'Industrie – Production', '#7a6f9c', '#efe9f3', 102),
  ('agriculture', 'Agriculture – Producteur local', '#c98a2e', '#f7efe0', 103),
  ('partenaire-institutionnel', 'Partenaire institutionnel – Collectivité', '#3f8aa3', '#e6eff2', 104)
ON CONFLICT ("slug") DO UPDATE SET "sort" = EXCLUDED."sort";
